FROM node:carbon
VOLUME  ["/myapp"]
WORKDIR /myapp
RUN apt-get update
#install project dependencies
RUN npm install -g gulp
RUN npm install -g bower
EXPOSE 3000
#install project dependencies when container starts
CMD npm install && bower install
